export const EventTypes = {
	ACTIVE_TAB_CHANGED: 'ACTIVE_TAB_CHANGED',
	GET_ACTIVE_TAB: 'GET_ACTIVE_TAB',
	RECOGNIZED_TEXT: 'RECOGNIZED_TEXT',

	GO_NEXT_TAB: 'GO_NEXT_TAB',
	GO_PREV_TAB: 'GO_PREV_TAB',
} as const;
